In [1]:
import nflreadpy as nfl

schedules = nfl.load_schedules(seasons=[2023])
schedules_pd = schedules.to_pandas()

schedules_pd.head()

,game_id,season,game_type,week,gameday,weekday,gametime,away_team,away_score,home_team,...,wind,away_qb_id,home_qb_id,away_qb_name,home_qb_name,away_coach,home_coach,referee,stadium_id,stadium
0,2023_01_DET_KC,2023,REG,1,2023-09-07,Thursday,20:20,DET,21,KC,...,NaN,00-0033106,00-0033873,Jared Goff,Patrick Mahomes,Dan Campbell,Andy Reid,John Hussey,KAN00,GEHA Field at Arrowhead Stadium
1,2023_01_CAR_ATL,2023,REG,1,2023-09-10,Sunday,13:00,CAR,10,ATL,...,NaN,00-0039150,00-0038122,Bryce Young,Desmond Ridder,Frank Reich,Arthur Smith,Brad Rogers,ATL97,Mercedes-Benz Stadium
2,2023_01_HOU_BAL,2023,REG,1,2023-09-10,Sunday,13:00,HOU,9,BAL,...,NaN,00-0039163,00-0034796,C.J. Stroud,Lamar Jackson,DeMeco Ryans,John Harbaugh,Tra Blake,BAL00,M&T Bank Stadium
3,2023_01_CIN_CLE,2023,REG,1,2023-09-10,Sunday,13:00,CIN,3,CLE,...,NaN,00-0036442,00-0033537,Joe Burrow,Deshaun Watson,Zac Taylor,Kevin Stefanski,Clete Blakeman,CLE00,FirstEnergy Stadium
4,2023_01_JAX_IND,2023,REG,1,2023-09-10,Sunday,13:00,JAX,31,IND,...,NaN,00-0036971,00-0039164,Trevor Lawrence,Anthony Richardson,Doug Pederson,Shane Steichen,Clay Martin,IND00,Lucas Oil Stadium

In [2]:
schedules_pd.info()

<class 'pandas.DataFrame'>
RangeIndex: 285 entries, 0 to 284
Data columns (total 46 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   game_id           285 non-null    str
 1   season            285 non-null    int32
 2   game_type         285 non-null    str
 3   week              285 non-null    int32
 4   gameday           285 non-null    str
 5   weekday           285 non-null    str
 6   gametime          285 non-null    str
 7   away_team         285 non-null    str
 8   away_score        285 non-null    int32
 9   home_team         285 non-null    str
 10  home_score        285 non-null    int32
 11  location          285 non-null    str
 12  result            285 non-null    int32
 13  total             285 non-null    int32
 14  overtime          285 non-null    int32
 15  old_game_id       285 non-null    str
 16  gsis              285 non-null    int32
 17  nfl_detail_id     0 non-null      str
 18  pfr               285 non-null    str
 19  pff               0 non-null      float64
 20  espn              285 non-null    str
 21  ftn               0 non-null      float64
 22  away_rest         285 non-null    int32
 23  home_rest         285 non-null    int32
 24  away_moneyline    285 non-null    int32
 25  home_moneyline    285 non-null    int32
 26  spread_line       285 non-null    float64
 27  away_spread_odds  285 non-null    int32
 28  home_spread_odds  285 non-null    int32
 29  total_line        285 non-null    float64
 30  under_odds        285 non-null    int32
 31  over_odds         285 non-null    int32
 32  div_game          285 non-null    int32
 33  roof              285 non-null    str
 34  surface           285 non-null    str
 35  temp              158 non-null    float64
 36  wind              158 non-null    float64
 37  away_qb_id        285 non-null    str
 38  home_qb_id        285 non-null    str
 39  away_qb_name      285 non-null    str
 40  home_qb_name      285 non-null    str
 41  away_coach        285 non-null    str
 42  home_coach        285 non-null    str
 43  referee           285 non-null    str
 44  stadium_id        285 non-null    str
 45  stadium           285 non-null    str
dtypes: float64(6), int32(17), str(23)
memory usage: 137.7 KB

In [3]:
schedules_pd.columns.tolist()

['game_id',
 'season',
 'game_type',
 'week',
 'gameday',
 'weekday',
 'gametime',
 'away_team',
 'away_score',
 'home_team',
 'home_score',
 'location',
 'result',
 'total',
 'overtime',
 'old_game_id',
 'gsis',
 'nfl_detail_id',
 'pfr',
 'pff',
 'espn',
 'ftn',
 'away_rest',
 'home_rest',
 'away_moneyline',
 'home_moneyline',
 'spread_line',
 'away_spread_odds',
 'home_spread_odds',
 'total_line',
 'under_odds',
 'over_odds',
 'div_game',
 'roof',
 'surface',
 'temp',
 'wind',
 'away_qb_id',
 'home_qb_id',
 'away_qb_name',
 'home_qb_name',
 'away_coach',
 'home_coach',
 'referee',
 'stadium_id',
 'stadium']

In [4]:
schedules_pd[["game_id", "game_type", "home_team", "away_team", "home_score", "away_score", "result", "home_coach", "away_coach"]].head(10)

,game_id,game_type,home_team,away_team,home_score,away_score,result,home_coach,away_coach
0,2023_01_DET_KC,REG,KC,DET,20,21,-1,Andy Reid,Dan Campbell
1,2023_01_CAR_ATL,REG,ATL,CAR,24,10,14,Arthur Smith,Frank Reich
2,2023_01_HOU_BAL,REG,BAL,HOU,25,9,16,John Harbaugh,DeMeco Ryans
3,2023_01_CIN_CLE,REG,CLE,CIN,24,3,21,Kevin Stefanski,Zac Taylor
4,2023_01_JAX_IND,REG,IND,JAX,21,31,-10,Shane Steichen,Doug Pederson
5,2023_01_TB_MIN,REG,MIN,TB,17,20,-3,Kevin O'Connell,Todd Bowles
6,2023_01_TEN_NO,REG,NO,TEN,16,15,1,Dennis Allen,Mike Vrabel
7,2023_01_SF_PIT,REG,PIT,SF,7,30,-23,Mike Tomlin,Kyle Shanahan
8,2023_01_ARI_WAS,REG,WAS,ARI,20,16,4,Ron Rivera,Jonathan Gannon
9,2023_01_GB_CHI,REG,CHI,GB,20,38,-18,Matt Eberflus,Matt LaFleur

In [5]:
import pandas as pd

player_stats = pd.read_csv("../data/raw/player_stats.csv")
player_stats.columns.tolist()
player_stats[player_stats["season"] == 2023]["week"].value_counts().sort_index()

C:\Users\jalou\AppData\Local\Temp\ipykernel_30224\4257153776.py:3: DtypeWarning: Columns (0: fg_missed_list, 1: fg_blocked_list) have mixed types. Specify dtype option on import or set low_memory=False.
  player_stats = pd.read_csv("../data/raw/player_stats.csv")

week
1     1058
2     1016
3     1037
4     1074
5      907
6      979
7      840
8     1052
9      946
10     925
11     894
12    1047
13     861
14    1004
15    1082
16    1042
17    1012
18    1030
19     388
20     258
21     122
22      69
Name: count, dtype: int64

In [6]:
player_stats.columns.tolist()

['player_id',
 'player_name',
 'player_display_name',
 'position',
 'position_group',
 'headshot_url',
 'season',
 'week',
 'season_type',
 'game_id',
 'team',
 'opponent_team',
 'completions',
 'attempts',
 'passing_yards',
 'passing_tds',
 'passing_interceptions',
 'sacks_suffered',
 'sack_yards_lost',
 'sack_fumbles',
 'sack_fumbles_lost',
 'passing_air_yards',
 'passing_yards_after_catch',
 'passing_first_downs',
 'passing_epa',
 'passing_cpoe',
 'passing_2pt_conversions',
 'pacr',
 'passing_10',
 'passing_16',
 'passing_20',
 'passing_40',
 'carries',
 'rushing_yards',
 'rushing_tds',
 'rushing_fumbles',
 'rushing_fumbles_lost',
 'rushing_first_downs',
 'rushing_epa',
 'rushing_2pt_conversions',
 'rushing_10',
 'rushing_12',
 'rushing_20',
 'rushing_40',
 'receptions',
 'targets',
 'receiving_yards',
 'receiving_tds',
 'receiving_fumbles',
 'receiving_fumbles_lost',
 'receiving_air_yards',
 'receiving_yards_after_catch',
 'receiving_first_downs',
 'receiving_epa',
 'receiving_2pt_conversions',
 'receiving_10',
 'receiving_16',
 'receiving_20',
 'receiving_40',
 'racr',
 'target_share',
 'air_yards_share',
 'wopr',
 'special_teams_tds',
 'def_tackles_solo',
 'def_tackles_with_assist',
 'def_tackle_assists',
 'def_tackles_for_loss',
 'def_tackles_for_loss_yards',
 'def_fumbles_forced',
 'def_sacks',
 'def_sack_yards',
 'def_qb_hits',
 'def_interceptions',
 'def_interception_yards',
 'def_pass_defended',
 'def_tds',
 'def_fumbles',
 'def_safeties',
 'def_punt_blocks',
 'def_pat_blocks',
 'def_fg_blocks',
 'def_2pt_atts',
 'def_2pt_made',
 'misc_yards',
 'fumble_recovery_own',
 'fumble_recovery_yards_own',
 'fumble_recovery_opp',
 'fumble_recovery_yards_opp',
 'fumble_recovery_tds',
 'penalties',
 'penalty_yards',
 'fumbles_forced_by_opp',
 'fumbles_not_forced',
 'fumbles_out_of_bounds',
 'fumbles_total',
 'fumbles_lost_total',
 'punt_returns',
 'punt_return_yards',
 'kickoff_returns',
 'kickoff_return_yards',
 'fg_made',
 'fg_att',
 'fg_missed',
 'fg_blocked',
 'fg_long',
 'fg_pct',
 'fg_made_0_19',
 'fg_made_20_29',
 'fg_made_30_39',
 'fg_made_40_49',
 'fg_made_50_59',
 'fg_made_60_',
 'fg_missed_0_19',
 'fg_missed_20_29',
 'fg_missed_30_39',
 'fg_missed_40_49',
 'fg_missed_50_59',
 'fg_missed_60_',
 'fg_made_list',
 'fg_missed_list',
 'fg_blocked_list',
 'fg_made_distance',
 'fg_missed_distance',
 'fg_blocked_distance',
 'pat_made',
 'pat_att',
 'pat_missed',
 'pat_blocked',
 'pat_pct',
 'gwfg_made',
 'gwfg_att',
 'gwfg_missed',
 'gwfg_blocked',
 'gwfg_distance',
 'pt_att',
 'pt_blocked',
 'pt_long',
 'pt_yards',
 'pt_inside_20',
 'pt_out_of_bounds',
 'pt_downed',
 'pt_touchback',
 'pt_fair_caught',
 'pt_returned',
 'pt_return_yards',
 'pt_return_tds',
 'pt_net_yards',
 'fantasy_points',
 'fantasy_points_ppr']

In [7]:
import pandas as pd

for name in ["schedules", "player_stats", "team_stats", "rosters"]:
    df = pd.read_csv(f"../data/raw/{name}.csv")
    print(name, df["season"].min(), df["season"].max())

schedules 2002 2025

C:\Users\jalou\AppData\Local\Temp\ipykernel_30224\1584053643.py:4: DtypeWarning: Columns (0: fg_missed_list, 1: fg_blocked_list) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f"../data/raw/{name}.csv")

player_stats 2002 2025
team_stats 2002 2025

C:\Users\jalou\AppData\Local\Temp\ipykernel_30224\1584053643.py:4: DtypeWarning: Columns (0: depth_chart_position, 1: jersey_number, 2: ngs_position) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f"../data/raw/{name}.csv")

rosters 2002 2025

In [8]:
team_stats = pd.read_csv("../data/raw/team_stats.csv")
team_stats.columns.tolist()

['season',
 'week',
 'team',
 'season_type',
 'game_id',
 'opponent_team',
 'completions',
 'attempts',
 'passing_yards',
 'passing_tds',
 'passing_interceptions',
 'sacks_suffered',
 'sack_yards_lost',
 'sack_fumbles',
 'sack_fumbles_lost',
 'passing_air_yards',
 'passing_yards_after_catch',
 'passing_first_downs',
 'passing_epa',
 'passing_cpoe',
 'passing_2pt_conversions',
 'passing_10',
 'passing_16',
 'passing_20',
 'passing_40',
 'carries',
 'rushing_yards',
 'rushing_tds',
 'rushing_fumbles',
 'rushing_fumbles_lost',
 'rushing_first_downs',
 'rushing_epa',
 'rushing_2pt_conversions',
 'rushing_10',
 'rushing_12',
 'rushing_20',
 'rushing_40',
 'receptions',
 'targets',
 'receiving_yards',
 'receiving_tds',
 'receiving_fumbles',
 'receiving_fumbles_lost',
 'receiving_air_yards',
 'receiving_yards_after_catch',
 'receiving_first_downs',
 'receiving_epa',
 'receiving_2pt_conversions',
 'receiving_10',
 'receiving_16',
 'receiving_20',
 'receiving_40',
 'special_teams_tds',
 'def_tackles_solo',
 'def_tackles_with_assist',
 'def_tackle_assists',
 'def_tackles_for_loss',
 'def_tackles_for_loss_yards',
 'def_fumbles_forced',
 'def_sacks',
 'def_sack_yards',
 'def_qb_hits',
 'def_interceptions',
 'def_interception_yards',
 'def_pass_defended',
 'def_tds',
 'def_fumbles',
 'def_safeties',
 'def_punt_blocks',
 'def_pat_blocks',
 'def_fg_blocks',
 'def_2pt_atts',
 'def_2pt_made',
 'misc_yards',
 'fumble_recovery_own',
 'fumble_recovery_yards_own',
 'fumble_recovery_opp',
 'fumble_recovery_yards_opp',
 'fumble_recovery_tds',
 'penalties',
 'penalty_yards',
 'timeouts',
 'fumbles_forced_by_opp',
 'fumbles_not_forced',
 'fumbles_out_of_bounds',
 'fumbles_total',
 'fumbles_lost_total',
 'punt_returns',
 'punt_return_yards',
 'kickoff_returns',
 'kickoff_return_yards',
 'fg_made',
 'fg_att',
 'fg_missed',
 'fg_blocked',
 'fg_long',
 'fg_pct',
 'fg_made_0_19',
 'fg_made_20_29',
 'fg_made_30_39',
 'fg_made_40_49',
 'fg_made_50_59',
 'fg_made_60_',
 'fg_missed_0_19',
 'fg_missed_20_29',
 'fg_missed_30_39',
 'fg_missed_40_49',
 'fg_missed_50_59',
 'fg_missed_60_',
 'fg_made_list',
 'fg_missed_list',
 'fg_blocked_list',
 'fg_made_distance',
 'fg_missed_distance',
 'fg_blocked_distance',
 'pat_made',
 'pat_att',
 'pat_missed',
 'pat_blocked',
 'pat_pct',
 'gwfg_made',
 'gwfg_att',
 'gwfg_missed',
 'gwfg_blocked',
 'gwfg_distance',
 'pt_att',
 'pt_blocked',
 'pt_long',
 'pt_yards',
 'pt_inside_20',
 'pt_out_of_bounds',
 'pt_downed',
 'pt_touchback',
 'pt_fair_caught',
 'pt_returned',
 'pt_return_yards',
 'pt_return_tds',
 'pt_net_yards']

In [9]:
schedules = pd.read_csv("../data/raw/schedules.csv")
print("schedules game_type values:", schedules["game_type"].unique())
print("team_stats season_type values:", team_stats["season_type"].unique())

schedules game_type values: <ArrowStringArray>
['REG', 'WC', 'DIV', 'CON', 'SB']
Length: 5, dtype: str
team_stats season_type values: <ArrowStringArray>
['REG', 'POST']
Length: 2, dtype: str

In [10]:
team_stats[team_stats["season_type"] == "POST"]["week"].unique()

array([18, 19, 20, 21, 22])

In [11]:
schedule_teams = set(schedules["home_team"].unique()) | set(schedules["away_team"].unique())
team_stats_teams = set(team_stats["team"].unique())

print("In schedules but not team_stats:", schedule_teams - team_stats_teams)
print("In team_stats but not schedules:", team_stats_teams - schedule_teams)

In schedules but not team_stats: {'STL', 'SD', 'OAK'}
In team_stats but not schedules: set()

In [12]:
team_stats[(team_stats["season"] == 2002) & (team_stats["team"].str.contains("JA"))]["team"].unique()

<ArrowStringArray>
['JAX']
Length: 1, dtype: str

In [13]:
missing_checks = [1, 4, 5, 8, 10, 13, 14, 16]

for week in missing_checks:
    match = team_stats[
        (team_stats["season"] == 2002)
        & (team_stats["week"] == week)
        & (team_stats["team"] == "JAX")
    ]
    print(f"week {week} -> rows found: {len(match)}")

week 1 -> rows found: 0
week 4 -> rows found: 0
week 5 -> rows found: 0
week 8 -> rows found: 0
week 10 -> rows found: 0
week 13 -> rows found: 0
week 14 -> rows found: 0
week 16 -> rows found: 0

In [14]:
import sys
from pathlib import Path

sys.path.append(str(Path.cwd().parent))

In [15]:
import pandas as pd
from src.config import DATA_RAW_DIR

team_stats = pd.read_csv(DATA_RAW_DIR / "team_stats.csv")

In [16]:
from src.features.build_team_history import compute_season_to_date_stats
result = compute_season_to_date_stats(team_stats)

check = result[(result["team"] == "KC") & (result["season"] == 2023)][["week", "passing_yards"]]
raw = team_stats[(team_stats["team"] == "KC") & (team_stats["season"] == 2023)][["week", "passing_yards"]]

print(raw)
print(check)

       week  passing_yards
11295     1            226
11327     2            305
11359     3            303
11391     4            203
11422     5            281
11450     6            306
11477     7            424
11507     8            240
11536     9            185
11593    11            177
11623    12            298
11652    13            210
11680    14            271
11711    15            309
11743    16            246
11775    17            245
11807    18            154
11830    19            262
11841    20            215
11846    21            241
11848    22            333
       week  passing_yards
11295     1            NaN
11327     2     226.000000
11359     3     265.500000
11391     4     278.000000
11422     5     259.250000
11450     6     263.600000
11477     7     270.666667
11507     8     292.571429
11536     9     286.000000
11593    11     274.777778
11623    12     265.000000
11652    13     268.000000
11680    14     263.166667
11711    15     263.769231
11743    16     267.000000
11775    17     265.600000
11807    18     264.312500
11830    19     257.823529
11841    20     258.055556
11846    21     255.789474
11848    22     255.050000

In [17]:
import pandas as pd
from src.config import DATA_RAW_DIR

schedules = pd.read_csv(DATA_RAW_DIR / "schedules.csv")

print(schedules["gameday"].dtype)
print(schedules["gameday"].head())

str
0    2002-09-05
1    2002-09-08
2    2002-09-08
3    2002-09-08
4    2002-09-08
Name: gameday, dtype: str

In [18]:
import sys
from pathlib import Path
sys.path.append(str(Path.cwd().parent))

import pandas as pd
from src.config import DATA_RAW_DIR
from src.features.build_team_history import compute_rest_days

schedules = pd.read_csv(DATA_RAW_DIR / "schedules.csv")
result = compute_rest_days(schedules)

print("Null home_rest_days:", result["home_rest_days"].isna().sum())
print("Null away_rest_days:", result["away_rest_days"].isna().sum())

kc_2023 = result[
    ((result["home_team"] == "KC") | (result["away_team"] == "KC"))
    & (result["season"] == 2023)
].sort_values("gameday")

print(kc_2023[["week", "gameday", "home_team", "home_rest_days", "away_team", "away_rest_days"]])

Null home_rest_days: 384
Null away_rest_days: 384
      week    gameday home_team  home_rest_days away_team  away_rest_days
5644     1 2023-09-07        KC             NaN       DET             NaN
5666     2 2023-09-17       JAX             7.0        KC            10.0
5688     3 2023-09-24        KC             7.0       CHI             7.0
5706     4 2023-10-01       NYJ             7.0        KC             7.0
5719     5 2023-10-08       MIN             7.0        KC             7.0
5722     6 2023-10-12        KC             4.0       DEN             4.0
5747     7 2023-10-22        KC            10.0       LAC             6.0
5762     8 2023-10-29       DEN             7.0        KC             7.0
5767     9 2023-11-05        KC             7.0       MIA             7.0
5807    11 2023-11-20        KC            15.0       PHI            15.0
5820    12 2023-11-26        LV             7.0        KC             6.0
5835    13 2023-12-03        GB            10.0        KC             7.0
5847    14 2023-12-10        KC             7.0       BUF            14.0
5860    15 2023-12-17        NE            10.0        KC             7.0
5881    16 2023-12-25        KC             8.0        LV            11.0
5898    17 2023-12-31        KC             6.0       CIN             8.0
5910    18 2024-01-07       LAC             7.0        KC             7.0
5917    19 2024-01-13        KC             6.0       MIA             6.0
5925    20 2024-01-21       BUF             6.0        KC             8.0
5926    21 2024-01-28       BAL             8.0        KC             7.0
5928    22 2024-02-11        KC            14.0        SF            14.0

In [20]:
import pandas as pd
from src.config import DATA_PROCESSED_DIR

df = pd.read_csv(DATA_PROCESSED_DIR / "game_features_team.csv")
print(df.shape)
print(df[["home_rest_days", "away_rest_days", "is_playoff"]].isna().sum())
print(df["is_playoff"].value_counts())

(6499, 313)
home_rest_days    384
away_rest_days    384
is_playoff          0
dtype: int64
is_playoff
0    6223
1     276
Name: count, dtype: int64

C:\Users\jalou\AppData\Local\Temp\ipykernel_30224\4033339101.py:4: DtypeWarning: Columns (0: nfl_detail_id, 1: home_fg_blocked_list, 2: away_fg_blocked_list) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(DATA_PROCESSED_DIR / "game_features_team.csv")