In [1]:
import nflreadpy as nfl

schedules = nfl.load_schedules(seasons=[2023])
schedules_pd = schedules.to_pandas()

schedules_pd.head()

,game_id,season,game_type,week,gameday,weekday,gametime,away_team,away_score,home_team,...,wind,away_qb_id,home_qb_id,away_qb_name,home_qb_name,away_coach,home_coach,referee,stadium_id,stadium
0,2023_01_DET_KC,2023,REG,1,2023-09-07,Thursday,20:20,DET,21,KC,...,NaN,00-0033106,00-0033873,Jared Goff,Patrick Mahomes,Dan Campbell,Andy Reid,John Hussey,KAN00,GEHA Field at Arrowhead Stadium
1,2023_01_CAR_ATL,2023,REG,1,2023-09-10,Sunday,13:00,CAR,10,ATL,...,NaN,00-0039150,00-0038122,Bryce Young,Desmond Ridder,Frank Reich,Arthur Smith,Brad Rogers,ATL97,Mercedes-Benz Stadium
2,2023_01_HOU_BAL,2023,REG,1,2023-09-10,Sunday,13:00,HOU,9,BAL,...,NaN,00-0039163,00-0034796,C.J. Stroud,Lamar Jackson,DeMeco Ryans,John Harbaugh,Tra Blake,BAL00,M&T Bank Stadium
3,2023_01_CIN_CLE,2023,REG,1,2023-09-10,Sunday,13:00,CIN,3,CLE,...,NaN,00-0036442,00-0033537,Joe Burrow,Deshaun Watson,Zac Taylor,Kevin Stefanski,Clete Blakeman,CLE00,FirstEnergy Stadium
4,2023_01_JAX_IND,2023,REG,1,2023-09-10,Sunday,13:00,JAX,31,IND,...,NaN,00-0036971,00-0039164,Trevor Lawrence,Anthony Richardson,Doug Pederson,Shane Steichen,Clay Martin,IND00,Lucas Oil Stadium

In [2]:
schedules_pd.info()

<class 'pandas.DataFrame'>
RangeIndex: 285 entries, 0 to 284
Data columns (total 46 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   game_id           285 non-null    str
 1   season            285 non-null    int32
 2   game_type         285 non-null    str
 3   week              285 non-null    int32
 4   gameday           285 non-null    str
 5   weekday           285 non-null    str
 6   gametime          285 non-null    str
 7   away_team         285 non-null    str
 8   away_score        285 non-null    int32
 9   home_team         285 non-null    str
 10  home_score        285 non-null    int32
 11  location          285 non-null    str
 12  result            285 non-null    int32
 13  total             285 non-null    int32
 14  overtime          285 non-null    int32
 15  old_game_id       285 non-null    str
 16  gsis              285 non-null    int32
 17  nfl_detail_id     0 non-null      str
 18  pfr               285 non-null    str
 19  pff               0 non-null      float64
 20  espn              285 non-null    str
 21  ftn               0 non-null      float64
 22  away_rest         285 non-null    int32
 23  home_rest         285 non-null    int32
 24  away_moneyline    285 non-null    int32
 25  home_moneyline    285 non-null    int32
 26  spread_line       285 non-null    float64
 27  away_spread_odds  285 non-null    int32
 28  home_spread_odds  285 non-null    int32
 29  total_line        285 non-null    float64
 30  under_odds        285 non-null    int32
 31  over_odds         285 non-null    int32
 32  div_game          285 non-null    int32
 33  roof              285 non-null    str
 34  surface           285 non-null    str
 35  temp              158 non-null    float64
 36  wind              158 non-null    float64
 37  away_qb_id        285 non-null    str
 38  home_qb_id        285 non-null    str
 39  away_qb_name      285 non-null    str
 40  home_qb_name      285 non-null    str
 41  away_coach        285 non-null    str
 42  home_coach        285 non-null    str
 43  referee           285 non-null    str
 44  stadium_id        285 non-null    str
 45  stadium           285 non-null    str
dtypes: float64(6), int32(17), str(23)
memory usage: 137.7 KB

In [3]:
schedules_pd.columns.tolist()

['game_id',
 'season',
 'game_type',
 'week',
 'gameday',
 'weekday',
 'gametime',
 'away_team',
 'away_score',
 'home_team',
 'home_score',
 'location',
 'result',
 'total',
 'overtime',
 'old_game_id',
 'gsis',
 'nfl_detail_id',
 'pfr',
 'pff',
 'espn',
 'ftn',
 'away_rest',
 'home_rest',
 'away_moneyline',
 'home_moneyline',
 'spread_line',
 'away_spread_odds',
 'home_spread_odds',
 'total_line',
 'under_odds',
 'over_odds',
 'div_game',
 'roof',
 'surface',
 'temp',
 'wind',
 'away_qb_id',
 'home_qb_id',
 'away_qb_name',
 'home_qb_name',
 'away_coach',
 'home_coach',
 'referee',
 'stadium_id',
 'stadium']

In [4]:
schedules_pd[["game_id", "game_type", "home_team", "away_team", "home_score", "away_score", "result", "home_coach", "away_coach"]].head(10)

,game_id,game_type,home_team,away_team,home_score,away_score,result,home_coach,away_coach
0,2023_01_DET_KC,REG,KC,DET,20,21,-1,Andy Reid,Dan Campbell
1,2023_01_CAR_ATL,REG,ATL,CAR,24,10,14,Arthur Smith,Frank Reich
2,2023_01_HOU_BAL,REG,BAL,HOU,25,9,16,John Harbaugh,DeMeco Ryans
3,2023_01_CIN_CLE,REG,CLE,CIN,24,3,21,Kevin Stefanski,Zac Taylor
4,2023_01_JAX_IND,REG,IND,JAX,21,31,-10,Shane Steichen,Doug Pederson
5,2023_01_TB_MIN,REG,MIN,TB,17,20,-3,Kevin O'Connell,Todd Bowles
6,2023_01_TEN_NO,REG,NO,TEN,16,15,1,Dennis Allen,Mike Vrabel
7,2023_01_SF_PIT,REG,PIT,SF,7,30,-23,Mike Tomlin,Kyle Shanahan
8,2023_01_ARI_WAS,REG,WAS,ARI,20,16,4,Ron Rivera,Jonathan Gannon
9,2023_01_GB_CHI,REG,CHI,GB,20,38,-18,Matt Eberflus,Matt LaFleur